"""World-model substrate and unified prediction contracts.

This package is NOT a world model. It is the data foundation and the
CONTRACT layer one needs before a world model can be built: frozen
pre-action belief snapshots, a unified record of the six action classes
(including the ones the OUTER agent performs), budget accounting, the links
between them, and the versioned prediction contracts that a model service
will later fill in.

Design rules inherited from the research consensus:

- Facts vs inference vs unknown: every key field carries an origin label
  and, where applicable, an evidence reference. Unknown is never written
  as a measured zero.
- Recommendation != selection != execution: a recall result is never
  auto-interpreted as a chosen plan; a chosen plan never fabricates
  execution quality.
- Real vs hypothetical: hypothetical branches are labelled
  ``source="hypothetical"`` and can never enter execution statistics or
  the knowledge-verification gate.
- The verification gate is absolute: nothing recorded here promotes a
  candidate into verified knowledge — that remains ``induce --verify``.
- No hidden calls, no background loops: everything is an explicit,
  stateless invocation against an explicit home, like the rest of the
  harness.

Prediction contracts (see :mod:`or_harness.world_model.contracts`):

- :class:`StrategyOutcomePrediction` — a candidate strategy's benefit,
  resource cost, risk and uncertainty;
- :class:`CapabilityEvolutionPrediction` — how a candidate learning
  operation would change future task performance, judged through
  observable consequences of ``H = F(M, W_OR, Pi, R, T)``.

Both are versioned, serializable and validatable, and both can be built
BEFORE a prediction service exists: the resulting object says
``contract_only`` rather than pretending a forecast was made.
"""

from or_harness.world_model.actions import (
    ACTION_TYPES,
    LEGACY_ACTION_TYPES,
    ActionLog,
    ActionRecord,
)
from or_harness.world_model.budget import BUDGET_STATUSES, BudgetLedger
from or_harness.world_model.contracts import (
    BASELINE_KINDS,
    BENEFIT_KINDS,
    CAPABILITY_EVIDENCE_STATUSES,
    CAPABILITY_SOURCES,
    CONTRACT_STATUSES,
    CONTRACT_VERSION,
    LEGACY_CONTRACT_VERSION,
    LEGACY_FIELD_MIGRATION,
    LEGACY_MODE_TO_KIND,
    LEGACY_STATUS_TO_CONTRACT_STATUS,
    LEGACY_UNMAPPABLE,
    LEGACY_UNMAPPABLE_SCOPES,
    PREDICTION_KINDS,
    PREDICTION_SCOPES,
    SERVICE_IMPLEMENTED_KINDS,
    SUPPORTED_CONTRACT_VERSIONS,
    BaselineStatement,
    BenefitEstimate,
    CandidateRef,
    CapabilityEvolutionPrediction,
    CapabilitySourceEvidence,
    EvidenceRef,
    ExpectedChange,
    ExpectedCost,
    ExperienceScope,
    HarnessCapabilityEvidence,
    LearningOperation,
    PredictionServiceStatus,
    PredictionTrace,
    RiskEvent,
    RiskStatement,
    StrategyOutcomePrediction,
    TaskTargeting,
    UncertaintyStatement,
    UnsupportedContractVersion,
    VerificationCondition,
    capability_evidence_from_legacy_harness_state,
    contract_status_from_legacy_status,
    detect_payload_version,
    legacy_prediction_view,
    load_contract_payload,
    prediction_kinds_for_mode,
    validate_capability_evolution,
    validate_capability_evidence,
    validate_strategy_outcome,
)
from or_harness.world_model.execution_window import (
    DEFAULT_AUXILIARY_ACTION_TYPES,
    DEFAULT_IN_SCOPE_ACTION_TYPES,
    WINDOW_ACTION_TYPES,
    WINDOW_ID_PREFIX,
    StrategyExecutionWindow,
    WindowIdentity,
    build_execution_window,
    parse_window_id,
    window_id_for,
    window_identity_problems,
)
from or_harness.world_model.context import (
    EVIDENCE_CLASSES,
    JOINT_REPRESENTATION_VERSION,
    MATH_ATTRIBUTE_ORIGINS,
    PREDICTION_CONTEXT_VERSION,
    RETRIEVAL_CHANNELS,
    JointProblemRepresentation,
    MathAttributes,
    PredictionContext,
    RetrievalView,
    UnsupportedContextVersion,
    build_context,
    build_joint_representation,
    build_retrieval_view,
    capability_evidence_with_sources,
    capability_version,
    cell_evidence_from_stats,
    classify_evidence,
    context_identity_problems,
    dedupe_evidence,
    effective_input_version,
    evidence_identity,
    frozen_knowledge_available,
    frozen_knowledge_view,
    knowledge_targets_from_context,
    math_attributes,
    memory_content_digest,
    resolve_effective_cir,
    retrieval_reuse_problems,
    snapshot_conditions,
    snapshot_from_context,
    structure_problems,
    task_with_effective_cir,
)
from or_harness.world_model.state import (
    BeliefSnapshot,
    KnowledgeRef,
    MAINTENANCE_TASK_ID,
    task_text,
    task_text_digest,
    verified_knowledge_view,
)
from or_harness.world_model.strategy_prediction import (
    STRATEGY_OUTCOME_PROTOCOL_VERSION,
    StrategyOutcomeService,
    build_strategy_outcome_request,
    parse_strategy_outcome_payload,
)
from or_harness.world_model.episode_closeout import (
    CALIBRATION_SUMMARY_VERSION,
    DEFAULT_MIN_CALIBRATION_SAMPLES,
    EPISODE_CLOSEOUT_VERSION,
    EPISODE_TERMINAL_STATES,
    EpisodeCloseout,
    RealOutcomeSummary,
    StrategyPredictionEvaluation,
    build_calibration_summary,
    calibration_summary_for_context,
    close_episode,
    evaluate_strategy_prediction,
    episode_closeout_record,
    summarize_real_outcome,
)
from or_harness.world_model.capability_evolution import (
    CAPABILITY_EVOLUTION_PROTOCOL_VERSION,
    CAPABILITY_EVOLUTION_SYSTEM_PROMPT,
    CapabilityEvolutionService,
    build_capability_evolution_request,
    learning_material_for_bundle,
    parse_capability_evolution_payload,
)
from or_harness.world_model.maintenance_decision import (
    CAPABILITY_EFFECT_VERSION,
    EFFECT_FINAL_STATES,
    EFFECT_STATES,
    EXECUTABLE_LEARNING_OPERATIONS,
    MAINTENANCE_COMPARISON_VERSION,
    MAINTENANCE_RECOMMENDATIONS,
    OBSERVABLE_CAPABILITY_METRICS,
    CapabilityEffectEvaluation,
    MaintenanceFactBinding,
    MaintenanceRecommendation,
    bind_maintenance_fact,
    capability_effect_summary,
    capability_evidence_from_effects,
    compare_capability_predictions,
    evaluate_capability_effect,
    get_effect_evaluation,
    get_maintenance_binding,
    get_paired_evaluation,
    record_effect_evaluation,
    record_maintenance_binding,
    record_paired_evaluation,
)

__all__ = [
    # state / actions / budget substrate
    "ACTION_TYPES",
    "LEGACY_ACTION_TYPES",
    "ActionLog",
    "ActionRecord",
    "BUDGET_STATUSES",
    "BudgetLedger",
    "BeliefSnapshot",
    "KnowledgeRef",
    "MAINTENANCE_TASK_ID",
    "task_text",
    "task_text_digest",
    "verified_knowledge_view",
    # strategy-outcome prediction service (M3, wm-so/1)
    "STRATEGY_OUTCOME_PROTOCOL_VERSION",
    "StrategyOutcomeService",
    "build_strategy_outcome_request",
    "parse_strategy_outcome_payload",
    # episode close-out and experience calibration (M4)
    "CALIBRATION_SUMMARY_VERSION",
    "DEFAULT_MIN_CALIBRATION_SAMPLES",
    "EPISODE_CLOSEOUT_VERSION",
    "EPISODE_TERMINAL_STATES",
    "EpisodeCloseout",
    "RealOutcomeSummary",
    "StrategyPredictionEvaluation",
    "build_calibration_summary",
    "calibration_summary_for_context",
    "close_episode",
    "evaluate_strategy_prediction",
    "episode_closeout_record",
    "summarize_real_outcome",
    # capability-evolution prediction service (M5, wm-ce/1)
    "CAPABILITY_EVOLUTION_PROTOCOL_VERSION",
    "CAPABILITY_EVOLUTION_SYSTEM_PROMPT",
    "CapabilityEvolutionService",
    "build_capability_evolution_request",
    "learning_material_for_bundle",
    "parse_capability_evolution_payload",
    # offline-improvement decision and two-stage capability feedback (M5)
    "CAPABILITY_EFFECT_VERSION",
    "EFFECT_FINAL_STATES",
    "EFFECT_STATES",
    "EXECUTABLE_LEARNING_OPERATIONS",
    "MAINTENANCE_COMPARISON_VERSION",
    "MAINTENANCE_RECOMMENDATIONS",
    "OBSERVABLE_CAPABILITY_METRICS",
    "CapabilityEffectEvaluation",
    "MaintenanceFactBinding",
    "MaintenanceRecommendation",
    "bind_maintenance_fact",
    "capability_effect_summary",
    "capability_evidence_from_effects",
    "compare_capability_predictions",
    "evaluate_capability_effect",
    "get_effect_evaluation",
    "get_maintenance_binding",
    "get_paired_evaluation",
    "record_effect_evaluation",
    "record_maintenance_binding",
    "record_paired_evaluation",
    # execution window (attempt vs strategy window)
    "DEFAULT_AUXILIARY_ACTION_TYPES",
    "DEFAULT_IN_SCOPE_ACTION_TYPES",
    "WINDOW_ACTION_TYPES",
    "WINDOW_ID_PREFIX",
    "StrategyExecutionWindow",
    "WindowIdentity",
    "build_execution_window",
    "window_id_for",
    "parse_window_id",
    "window_identity_problems",
    # prediction input context (phase 2)
    "PREDICTION_CONTEXT_VERSION",
    "JOINT_REPRESENTATION_VERSION",
    "MATH_ATTRIBUTE_ORIGINS",
    "RETRIEVAL_CHANNELS",
    "EVIDENCE_CLASSES",
    "PredictionContext",
    "JointProblemRepresentation",
    "MathAttributes",
    "RetrievalView",
    "UnsupportedContextVersion",
    "build_context",
    "build_joint_representation",
    "build_retrieval_view",
    "capability_evidence_with_sources",
    "capability_version",
    "cell_evidence_from_stats",
    "classify_evidence",
    "context_identity_problems",
    "dedupe_evidence",
    "effective_input_version",
    "evidence_identity",
    "frozen_knowledge_available",
    "frozen_knowledge_view",
    "knowledge_targets_from_context",
    "math_attributes",
    "memory_content_digest",
    "resolve_effective_cir",
    "retrieval_reuse_problems",
    "snapshot_conditions",
    "snapshot_from_context",
    "structure_problems",
    "task_with_effective_cir",
    # unified contracts
    "CONTRACT_VERSION",
    "LEGACY_CONTRACT_VERSION",
    "SUPPORTED_CONTRACT_VERSIONS",
    "PREDICTION_KINDS",
    "SERVICE_IMPLEMENTED_KINDS",
    "CONTRACT_STATUSES",
    "PREDICTION_SCOPES",
    "BENEFIT_KINDS",
    "BASELINE_KINDS",
    "CAPABILITY_SOURCES",
    "CAPABILITY_EVIDENCE_STATUSES",
    "LEGACY_FIELD_MIGRATION",
    "LEGACY_MODE_TO_KIND",
    "LEGACY_STATUS_TO_CONTRACT_STATUS",
    "LEGACY_UNMAPPABLE",
    "LEGACY_UNMAPPABLE_SCOPES",
    "PredictionServiceStatus",
    "StrategyOutcomePrediction",
    "CapabilityEvolutionPrediction",
    "CandidateRef",
    "BenefitEstimate",
    "ExpectedCost",
    "RiskEvent",
    "RiskStatement",
    "UncertaintyStatement",
    "PredictionTrace",
    "EvidenceRef",
    "HarnessCapabilityEvidence",
    "CapabilitySourceEvidence",
    "LearningOperation",
    "ExperienceScope",
    "TaskTargeting",
    "BaselineStatement",
    "ExpectedChange",
    "VerificationCondition",
    "UnsupportedContractVersion",
    "validate_capability_evolution",
    "validate_capability_evidence",
    "validate_strategy_outcome",
    "detect_payload_version",
    "load_contract_payload",
    "legacy_prediction_view",
    "capability_evidence_from_legacy_harness_state",
    "contract_status_from_legacy_status",
    "prediction_kinds_for_mode",
]

